Added feature to display individual input validation errors, fixes #552
MasoniteFramework/masonite pull request #553
Opened 2022-03-05 06:09 UTC by yubarajshrestha

2022-03-07 10:16 UTC, girardinsamuel requested changes
IMO, this would be better to do it in its own middleware to allow a user to disable sharing validation errors.

Also errors are already shared in session through `errors` key. I would directly use this key instead of using `validation_errors` key.

So maybe, we should mix both of those approach in `ShareErrorsInSession` middleware:

- Put sharing errors logic in this middleware
- Map errors with MessageBag as you did.

We would end up with something like this:
```python

class ShareErrorsInSessionMiddleware(Middleware):
    def before(self, request, response):
         request.app.make("view").share(
                {
                    "errors": MessageBag(Session.pull("errors") or {}),
                }
            )
        return request

    def after(self, request, _):
        return request
```

2022-03-07 16:26 UTC, yubarajshrestha reviewed
Created separate middleware to handle errors in frontend...

2022-03-07 16:39 UTC, girardinsamuel requested changes

2022-03-07 16:39 UTC, girardinsamuel commented on src/masonite/middleware/route/ShareErrorsInSessionMiddleware.py
> +        request.app.make("request").session = Session
You should not need to do this 🤔

2022-03-07 16:39 UTC, girardinsamuel commented on src/masonite/views/view.py
> +    def reset_vaidation_errors(self):
```suggestion
    def reset_validation_errors(self):
```

2022-03-08 06:00 UTC, yubarajshrestha commented on src/masonite/middleware/route/ShareErrorsInSessionMiddleware.py
> +        request.app.make("request").session = Session
Ah Fixed...

2022-03-08 06:02 UTC, yubarajshrestha commented on src/masonite/views/view.py
> +    def reset_vaidation_errors(self):
Actually we do not need that part anymore so I am removing that method.

2022-03-08 08:29 UTC, yubarajshrestha reviewed
Fixed requested changes.

2022-03-21 08:44 UTC, girardinsamuel commented
I took a look again here and I would like to add a unit test.
So I added a unit test and I got an error..I need to look a bit into it, I will try to solve this soon !

2022-04-11 01:48 UTC, josephmancuso commented
whats going on with this PR? is it good?

2022-04-11 07:59 UTC, girardinsamuel commented
Hmm for now there is something with the unit test I wrote, I don't know if the issue is coming from tests or from the framework itself. I will push this so we can discuss it.

2022-04-23 07:22 UTC, yubarajshrestha commented
@josephmancuso @girardinsamuel what's the status for this PR? Any issues? It's working perfectly in my case in all of my applications.

2022-04-23 07:24 UTC, girardinsamuel commented
> what's the status for this PR? Any issues? It's working perfectly in my case in all of my applications.

I was waiting for the last release to be made, to hopefully fix the unit tests I pushed to this PR.
And I will need to review it again.

2022-04-24 21:15 UTC, josephmancuso commented
Put this branch up to date with 4.0

2022-04-24 21:17 UTC, josephmancuso commented
> @josephmancuso @girardinsamuel what's the status for this PR? Any issues? It's working perfectly in my case in all of my applications.

@yubarajshrestha what's preventing me from merging it really is that failing test.

2022-04-24 21:23 UTC, girardinsamuel commented
It's a test I have added. I will remove it for now

2022-04-25 08:25 UTC, girardinsamuel approved these changes
That's okay for me for now. 
In Masonite 5, maybe we will need to refactor session flashing and message bag validation features.

2022-04-28 02:09 UTC, josephmancuso approved these changes

2022-04-28 02:09 UTC, merged